### PR TITLE
bug fix with Interscript 1.0.5

### PR DESCRIPTION
**Pull request by webdev778**
## Changes
-   [interscript-js](https://github.com/interscript/interscript-js) has been updated the version from 1.0.3 to 1.0.5, obviously including a fix of the [issue 15](https://github.com/interscript/interscript-js/issues/15)

- load JSON data of system maps via asynchronously instead of require

## ScreenShots
image

## What should do after merge

 - yarn install
 - _**copy system map json files under public/maps**_

### CODE REVIEW

**Comment by strogonoff** [comment]
@webdev778 

Interscript.com landing page, for the sake of stability and reducing page size, should not have extra dependencies added beyond what is already here, and can use Interscript functionality through API only. This _particularly_ applies to interscript.js library, which can still be unstable in browser environment, and which makes client side download bigger by almost 5 megabytes.

We will have the UN poster demo of full interscript.js library capabilities as a separate mini-site, likely on a subdomain. That mini-site is allowed to directly include interscript.js and any other dependencies. It will not be required to use React.js and react-static based build workflow. It will be open to modifications without my review. I have created a blank repo for the UN poster demo at https://github.com/interscript/un-poster-demo.

cc @ronaldtse

**Comment by strogonoff** [comment]
With above in mind, demo code that involves interscript.js library should be added to that newly created mini-site repository, I don’t think it will go to interscript.com site itself.

**Comment by ronaldtse** [comment]
@strogonoff we will not only need the UN poster, but also other posters (BGN/PCGN, ALA-LC, etc) by authority. Are you thinking of a separate subdomain or at something like `www.interscript.com/posters`?

**Comment by ronaldtse** [comment]
@webdev778 I've discussed with @strogonoff and we've created a new repo at https://github.com/interscript/jsdemo.interscript.com for a new site "jsdemo.interscript.com".

Can you help move this code (the UN poster) there as an entirely new site? A static site could work (no need for a build stack if we want to show users how simple it is).

**Comment by webdev778** [comment]
> @webdev778
> 
> Interscript.com landing page, for the sake of stability and reducing page size, should not have extra dependencies added beyond what is already here, and can use Interscript functionality through API only. This _particularly_ applies to interscript.js library, which can still be unstable in browser environment, and which makes client side download bigger by almost 5 megabytes.
> 
> We will have the UN poster demo of full interscript.js library capabilities as a separate mini-site, likely on a subdomain. That mini-site is allowed to directly include interscript.js and any other dependencies. It will not be required to use React.js and react-static based build workflow. It will be open to modifications without my review. I have created a blank repo for the UN poster demo at https://github.com/interscript/un-poster-demo.
> 
> cc @ronaldtse

**Comment by webdev778** [comment]
> @webdev778
> 
> Interscript.com landing page, for the sake of stability and reducing page size, should not have extra dependencies added beyond what is already here, and can use Interscript functionality through API only. This _particularly_ applies to interscript.js library, which can still be unstable in browser environment, and which makes client side download bigger by almost 5 megabytes.
> 
> We will have the UN poster demo of full interscript.js library capabilities as a separate mini-site, likely on a subdomain. That mini-site is allowed to directly include interscript.js and any other dependencies. It will not be required to use React.js and react-static based build workflow. It will be open to modifications without my review. I have created a blank repo for the UN poster demo at https://github.com/interscript/un-poster-demo.
> 
> cc @ronaldtse

@strogonoff 
I'm concerning the size on interscript-js library either. it's getting bigger as including map files.
In order to resolve the size issue, I it's already unbundled js maps seperately from interscript.js so it's size only 1,8M (which you can think still big). I agree with your idea to seperate example websites for each ruby and javascript.

**Pull request closed without merging**
